name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install tinypy
        run: uv sync --all-extras --dev

      - name: Run tests
        run: chmod +x test.sh && ./test.sh
